services:
  inner-x10Bot-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - x10-inner-bot_redis_data:/data
    restart: always

  inner-x10Bot-app:
    image: node:18-alpine
    working_dir: /usr/src/app  
    volumes:
      - .:/usr/src/app  
    command: sh -c "npm install && npm start"
    environment:
      - REDIS_HOST=inner-x10Bot-redis
      - PGHOST=inner-x10Bot-postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - inner-x10Bot-redis
      - inner-x10Bot-postgres
    ports:
      - "3001:3000"
    restart: always

  inner-x10Bot-postgres:
    image: postgres:15-alpine
    container_name: inner-x10Bot-postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGNAME}
    ports:
      - "5432:5432"
    volumes:
      - x10-inner-bot_postgres_data:/var/lib/postgresql/data
    restart: always

  inner-x10Bot-report-service:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm install -g typescript && npm run build && node dist/src/services/reportService.js"
    environment:
      - PGHOST=inner-x10Bot-postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - inner-x10Bot-postgres
    restart: always
  
volumes:
  x10-inner-bot_redis_data:
  x10-inner-bot_postgres_data: