services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  app:
    image: node:18-alpine
    working_dir: /usr/src/app  
    volumes:
      - .:/usr/src/app  
    command: sh -c "npm ci && npm start"
    environment:
      - REDIS_HOST=redis
      - PGHOST=postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
    ports:
      - "3001:3000"
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  report-service:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm ci && npm run build && npm start"
    environment:
      - REDIS_HOST=redis
      - PGHOST=postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
    restart: always

  migration:
    image: node:18-alpine
    working_dir: /usr/src/database
    volumes:
      - .:/usr/src/database
    command: sh -c "sleep 10 && npm run migrate"
    environment:
      - PGHOST=postgres
      - PGUSER=${PGUSER}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - postgres
    restart: "no"

volumes:
  redis_data:
  postgres_data: